# mysql listening on port 3306
# redis listening on port 6379
# service-end listening on port 8080
version: '2.2'

services:
  gateway:
    image: txzdream/go-online-front_end:dev
    volumes:
      # - /server/script/dev/nginx:/etc/nginx/conf.d:ro
      # - /server/static/dev:/data/static
      - /home/tangxuanzhao/Documents/development/go-online/script/nginx:/etc/nginx/conf.d:ro
      - /home/tangxuanzhao/Documents/development/go-online/static:/data/static
    ports:
      - 80:80
    links:
      - mysql_client
      - user-gateway
      - project-service
      - auth-service
      - ws-service
      - file-service
      - static-service
      - user-service
    networks:
      - user-services
      - default
    

  user-service:
    image: txzdream/go-online-user_service:dev
    environment:
      - DEVELOP=true
      - PORT=8080
      - DOCKER_ADDRESS=docker-service
      - DOCKER_PORT=8888
      - DATABASE_ADDRESS=mysql
      - DATABASE_PORT=3306
      - REDIS_ADDRESS=redis
      - REDIS_PORT=6379
      - CONSUL_ADDRESS=user-consul
      - CONSUL_PORT=8500
    volumes:
      - /home:/home
    expose:
      - 8080
    links:
      - docker-service
      - mysql
      - redis
      - user-consul
    networks:
      - user-services
      - default

  project-service:
    image: txzdream/go-online-project_service:dev
    environment:
      - DEVELOP=true
      - PORT=8080
      - DOCKER_ADDRESS=docker-service
      - DOCKER_PORT=8888
      - DATABASE_ADDRESS=mysql
      - DATABASE_PORT=3306
      - REDIS_ADDRESS=redis
      - REDIS_PORT=6379
      - CONSUL_ADDRESS=user-consul
      - CONSUL_PORT=8500
    volumes:
      - /home:/home
    expose:
      - 8080
    links:
      - docker-service
      - mysql
      - redis
      - user-consul
    networks:
      - user-services
      - default

  auth-service:
    image: txzdream/go-online-auth_service:dev
    environment:
      - DEVELOP=true
      - PORT=8080
      - DOCKER_ADDRESS=docker-service
      - DOCKER_PORT=8888
      - DATABASE_ADDRESS=mysql
      - DATABASE_PORT=3306
      - REDIS_ADDRESS=redis
      - REDIS_PORT=6379
      - CONSUL_ADDRESS=user-consul
      - CONSUL_PORT=8500
    volumes:
      - /home:/home
    expose:
      - 8080
    links:
      - docker-service
      - mysql
      - redis
      - user-consul
    networks:
      - user-services
      - default

  file-service:
    image: txzdream/go-online-file_service:dev
    environment:
      - DEVELOP=true
      - PORT=8080
      - DOCKER_ADDRESS=docker-service
      - DOCKER_PORT=8888
      - DATABASE_ADDRESS=mysql
      - DATABASE_PORT=3306
      - REDIS_ADDRESS=redis
      - REDIS_PORT=6379
      - CONSUL_ADDRESS=user-consul
      - CONSUL_PORT=8500
    volumes:
      - /home:/home
    expose:
      - 8080
    links:
      - docker-service
      - mysql
      - redis
      - user-consul
    networks:
      - user-services
      - default
  
  ws-service:
    image: txzdream/go-online-ws_service:dev
    environment:
      - DEVELOP=true
      - PORT=8080
      - DOCKER_ADDRESS=docker-service
      - DOCKER_PORT=8888
      - DATABASE_ADDRESS=mysql
      - DATABASE_PORT=3306
      - REDIS_ADDRESS=redis
      - REDIS_PORT=6379
      - CONSUL_ADDRESS=user-consul
      - CONSUL_PORT=8500
    volumes:
      - /home:/home
    expose:
      - 8080
    links:
      - docker-service
      - mysql
      - redis
      - user-consul
    networks:
      - user-services
      - default

  static-service:
    image: txzdream/go-online-static_end:dev
    environment:
      - DEVELOP=true
      - PORT=8080
      - DOCKER_ADDRESS=docker-service
      - DOCKER_PORT=8888
      - DATABASE_ADDRESS=mysql
      - DATABASE_PORT=3306
      - REDIS_ADDRESS=redis
      - REDIS_PORT=6379
      - CONSUL_ADDRESS=user-consul
      - CONSUL_PORT=8500
    volumes:
      - /home:/home
    expose:
      - 8080
    links:
      - docker-service
      - mysql
      - redis
      - user-consul
    networks:
      - user-services
      - default

  docker-service:
    image: txzdream/go-online-docker_end:dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - 8888
    environment:
      - PORT=8888

  mysql:
    image: mysql:5.6
    volumes:
      - /home/tangxuanzhao/Documents/development/go-online/mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
        
  mysql_client:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_ABSOLUTE_URI=/db
    links:
      - mysql

  redis:
    image: redis
    volumes:
      - /home/tangxuanzhao/Documents/development/go-online/redis:/data
    ports:
      - 6379:6379

  user-consul:
    image: consul
    command: 'agent -server -bootstrap-expect 3 -disable-host-node-id -client 0.0.0.0 -ui'
    scale: 1
    ports:
      - '8400:8400'
      - '8500:8500'
      - '8600:8600/udp'
    networks:
      - user-services

  consul-worker:
    image: consul
    user: root
    command: 'agent -server -join user-consul -disable-host-node-id -client 0.0.0.0 -ui'
    scale: 2
    links:
      - user-consul
    networks:
      - user-services

  user-gateway:
    image: txzdream/go-online-user-service-proxy:dev
    expose:
      - 8081
    links:
      - user-consul
    environment:
      - DEVELOP=true
      - CONSUL_ADDRESS=user-consul
      - CONSUL_PORT=8500
      - DOMAIN_NAME=localhost
    networks:
      - user-services

networks: 
  user-services:
    driver: bridge
