# mysql listening on port 3306
# redis listening on port 6379
# service-end listening on port 8080
version: '2'

services:
  service-end:
    image: txzdream/go-online-service_end:dev
    environment:
      - DEVELOP=true
      - PORT=8080
      - DOCKER_ADDRESS=docker-service
      - docker_PORT=8888
    volumes:
      - /home:/home
    expose:
      - 8080
    links:
      - docker-service

  docker-service:
    image: txzdream/go-online-docker_end:dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - 8888
    environment:
      - PORT=8888

  dev_gateway:
    image: txzdream/go-online-front_end:dev
    volumes:
      # - /server/script/dev/nginx:/etc/nginx/conf.d:ro
      # - /server/static/dev:/data/static
      - /home/tangxuanzhao/Documents/development/go-online/script/nginx:/etc/nginx/conf.d:ro
      - /home/tangxuanzhao/Documents/development/go-online/static:/data/static
    ports:
      - 80:80
    links:
      - service-end