# mysql listening on port 3306
# redis listening on port 6379
# service-end listening on port 8080
version: '2'

services:
  service-end:
    image: txzdream/go-online-service_end:dev
    environment:
      - DEVELOP=true
      - PORT=8080
      - DOCKER_ADDRESS=docker-service
      - docker_PORT=8888
    volumes:
      - /server/home:/home
    expose:
      - 8080
    links:
      - docker-service
    networks:
      - own

  docker-service:
    image: txzdream/go-online-docker_end:dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    exposes:
      - 8888
    environments:
      - PORT=8888
    networks:
      - own

  dev_gateway:
    image: txzdream/go-online-front_end:dev
    volumes:
      - /server/script/dev/nginx:/etc/nginx/conf.d:ro
      - /server/static/dev:/data/static
    ports:
      - 80:80
    links:
      - service-end
    networks:
      - share
      - own

networks:
  own:
    external:
      name: dev
  share:
    external:
      name: activity
    