# mysql listening on port 3306
# redis listening on port 6379
# service-end listening on port 8080
version: '2'

services:
  # redis:
  #   image: redis
  #   volumes:
  #     - /server/data/dev/redis:/data/
  #   networks:
  #     - own

  # mysql:
  #   image: mysql:5.6
  #   volumes:
  #     - /server/data/dev/mysql:/var/lib/mysql
  #   environment:
  #       MYSQL_ROOT_PASSWORD: root
  #   networks:
  #     - own
        
  # mysql_client:
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     - PMA_HOST=mysql
  #     - PMA_ABSOLUTE_URI=/db
  #   links:
  #     - mysql
  #   networks:
  #     - own

  service-end:
    image: txzdream/go-online-service_end:dev
    environment:
      - DEVELOP=true
      - PORT=8080
      - DATABASE_ADDRESS=mysql
      - DATABASE_PORT=3306
      - DOCKER_ADDRESS=docker-service
      - docker_PORT=8888
    volumes:
      - /server/home:/home
    # links:
    #   - redis
    #   - mysql
      # - docker-service
    expose:
      - 8080
    networks:
      - own

# docker service is required
  # docker-service:

  dev_gateway:
    image: txzdream/go-online-front_end:dev
    volumes:
      - /server/script/dev/nginx:/etc/nginx:ro
      - /server/static/dev:/data/static
    ports:
      - 80:80
    links:
      - service-end
      # - mysql_client
    networks:
      - share
      - own

networks:
  own:
    external:
      name: dev
  share:
    external:
      name: activity
    