# mysql listening on port 3306
# redis listening on port 6379
# service-end listening on port 8080
version: '2'

services:
  service-end:
    image: txzdream/go-online-service_end:dev
    environment:
      - DEVELOP=true
      - PORT=8080
      - DOCKER_ADDRESS=docker-service
      - DOCKER_PORT=8888
      - DATABASE_ADDRESS=mysql
      - DATABASE_PORT=3306
      - REDIS_ADDRESS=redis
      - REDIS_PORT=6379
    volumes:
      - /home:/home
    expose:
      - 8080
    links:
      - docker-service
      - mysql
      - redis

  docker-service:
    image: txzdream/go-online-docker_end:dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - 8888
    environment:
      - PORT=8888

  dev_gateway:
    image: txzdream/go-online-front_end:dev
    volumes:
      # - /server/script/dev/nginx:/etc/nginx/conf.d:ro
      # - /server/static/dev:/data/static
      - /home/tangxuanzhao/Documents/development/go-online/script/nginx:/etc/nginx/conf.d:ro
      - /home/tangxuanzhao/Documents/development/go-online/static:/data/static
    ports:
      - 80:80
    links:
      - service-end
      - mysql_client
      - redis_client

  mysql:
    image: mysql:5.6
    volumes:
      - /home/tangxuanzhao/Documents/development/go-online/mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
        
  mysql_client:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_ABSOLUTE_URI=/db
    links:
      - mysql

  redis:
    image: redis
    volumes:
      - /home/tangxuanzhao/Documents/development/go-online/redis:/data
    ports:
      - 6379:6379

  redis_client:
    image: marian/rebrow
    ports:
      - 5001:5001
    links:
      - redis

